// <auto-generated />
namespace MyShop2.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updateBasketModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateBasketModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202006031509181_updateBasketModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
