// <auto-generated />
namespace MyShop2.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class basket : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(basket));
        
        string IMigrationMetadata.Id
        {
            get { return "202005312356426_basket"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
